### ISSUE TITLE
Add theme support to the components

### ISSUE THREAD

**Issue by jtanner** [mxenabled/mx-react-components#588]
We need to add theming to our components which will allow customizing more than just the `primaryColor`. 

- [x] move functions in `constants/Style.js` to `utils/Style.js` #589 
- [x] add a theme merge function to `utils/Style.js` #592
- [x] move unused category colors and `LIGHT_*` colors to a different repo
- [x] deprecate unused colors #591 
- [x] add theme prop to all components #648 
- [x] remove primaryColor prop from all components #648 

### New theme names mapping
```javascript
    // Accent Colors
    primary: 'PRIMARY',
    success: 'LIME',
    warning: 'BANANA',
    danger: 'STRAWBERRY',
    attention: 'ORANGE',
    // Light Accent Colors
    light_success: 'LIGHT_LIME',
    light_warning: 'LIGHT_BANANA',
    light_danger: 'LIGHT_STRAWBERRY',
    // Gray Scale
    gray_100: 'PORCELAIN',
    gray_300: 'FOG',
    gray_500: 'ASH',
    gray_700: 'CHARCOAL',
    gray_900: 'SLATE',
```

**Comment by jtanner** [comment]
Here are the components that need the `theme` prop:
- [ ] BarChart.js
- [ ] Button.js
- [ ] ButtonGroup.js
- [ ] Calendar.js
- [ ] DatePicker.js
- [ ] DatePickerFullScreen.js
- [ ] DateRangePicker.js
- [ ] DateTimePicker.js
- [ ] DisplayInput.js
- [ ] DonutChart.js
- [ ] Drawer.js
- [ ] FileUpload.js
- [ ] Gauge.js
- [ ] HeaderMenu.js
- [ ] Icon.js
- [ ] Loader.js
- [ ] Menu.js
- [ ] MessageBox.js
- [ ] Modal.js
- [ ] NotifyOnScrollThreshold.js
- [ ] PageIndicator.js
- [ ] PaginationButtons.js
- [ ] ProgressBar.js
- [ ] RadioButton.js
- [ ] RajaIcon.js
- [ ] RangeSelector.js
- [ ] SearchInput.js
- [ ] Select.js
- [ ] SelectFullScreen.js
- [ ] SimpleInput.js
- [ ] SimpleSelect.js
- [ ] SimpleSlider.js
- [ ] Spin.js
- [ ] Tabs.js
- [ ] TextArea.js
- [ ] TimeBasedLineChart.js
- [ ] ToggleSwitch.js
- [ ] Tooltip.js
- [ ] TypeAhead.js
- [ ] Listbox.js
- [ ] AxisGroup.js
- [ ] BarTimeXAxis.js
- [ ] BreakPointGroup.js
- [ ] CirclesGroup.js
- [ ] GridLinesGroup.js
- [ ] LineGroup.js
- [ ] ShadedAreaRectangleGroup.js
- [ ] ShadedHatchPatternRectangleGroup.js
- [ ] SlicesGroup.js
- [ ] TimeXAxisGroup.js
- [ ] Column.js
- [ ] Container.js
- [ ] Row.js

**Comment by jtanner** [comment]
These components need `primaryColor` replaced with `theme` everywhere they're referenced:
- [ ] BarChart.js
- [ ] Button.js
- [ ] ButtonGroup.js
- [ ] Calendar.js
- [ ] DatePicker.js
- [ ] DatePickerFullScreen.js
- [ ] DateRangePicker.js
- [ ] DateTimePicker.js
- [ ] DisplayInput.js
- [ ] DonutChart.js
- [ ] Drawer.js
- [ ] FileUpload.js
- [ ] Gauge.js
- [ ] Loader.js
- [ ] Menu.js
- [ ] MessageBox.js
- [ ] Modal.js
- [ ] PageIndicator.js
- [ ] PaginationButtons.js
- [ ] ProgressBar.js
- [ ] RadioButton.js
- [ ] RangeSelector.js
- [ ] SearchInput.js
- [ ] Select.js
- [ ] SelectFullScreen.js
- [ ] SimpleInput.js
- [ ] SimpleSelect.js
- [ ] SimpleSlider.js
- [ ] Tabs.js
- [ ] TextArea.js
- [ ] TimeBasedLineChart.js
- [ ] ToggleSwitch.js
- [ ] Tooltip.js
- [ ] TypeAhead.js
- [ ] BarTimeXAxis.js
- [ ] CirclesGroup.js
- [ ] LineGroup.js
- [ ] ShadedAreaRectangleGroup.js
- [ ] ShadedHatchPatternRectangleGroup.js

**Comment by jtanner** [comment]
This was released with v5.0.0
